version: "3.1"

services:
  bondage-academy-server:
    image: bondage-academy-server:latest
    container_name: bondage-academy-server
    ports:
      - 3000:3000
    environment:
      MONGODB_CONNECTION_STRING: mongodb://root:root@mongodb:27017/admin?replicaSet=rs0
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaSetKey
      MONGODB_ADVERTISED_HOSTNAME: mongodb
    volumes:
      - "mongodb_data:/bitnami/mongodb"

volumes:
  mongodb_data:
    driver: local
