version: "3.1"

services:
  caddy:
    image: ghcr.io/xenonrope/bondage-academy-client:latest
    container_name: bondage-academy-client
    ports:
      - 80:80
      - 443:443
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"

  bondage-academy-server:
    image: ghcr.io/xenonrope/bondage-academy-server:latest
    container_name: bondage-academy-server
    environment:
      MONGODB_CONNECTION_STRING: mongodb://root:root@mongodb:27017/admin?replicaSet=rs0
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb:7.0
    container_name: mongodb
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaSetKey
      MONGODB_ADVERTISED_HOSTNAME: mongodb
    volumes:
      - "mongodb_data:/bitnami/mongodb"

volumes:
  mongodb_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
