FROM caddy:2.7-alpine

LABEL org.opencontainers.image.source https://github.com/XenonRope/BondageAcademy

COPY apps/bondage-academy-client/Caddyfile /etc/caddy/Caddyfile
COPY dist/apps/bondage-academy-client/ /usr/share/caddy/
