name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Restore cached node_modules
        uses: actions/cache/restore@v4
        with:
          path: |
            bondage-academy/node_modules
          key: node_modules-${{ hashFiles('bondage-academy/pnpm-lock.yaml') }}
      - name: Install dependencies
        working-directory: ./bondage-academy
        run: pnpm install --frozen-lockfile
      - name: Cache node_modules
        uses: actions/cache/save@v4
        with:
          path: |
            bondage-academy/node_modules
          key: node_modules-${{ hashFiles('bondage-academy/pnpm-lock.yaml') }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: master
      - name: Build, test and lint
        working-directory: ./bondage-academy
        run: pnpm nx affected -t build test lint --parallel=3
