name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./bondage-academy/node_modules
          key: node_modules-${{ hashFiles('bondage-academy/pnpm-lock.yaml') }}
      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: ./bondage-academy/.nx
          key: nx-${{ hashFiles('bondage-academy/pnpm-lock.yaml') }}-${{github.ref_name}}-${{ github.sha }}
          restore-keys: |
            nx-${{ hashFiles('bondage-academy/pnpm-lock.yaml') }}-${{github.ref_name}}-
            nx-${{ hashFiles('bondage-academy/pnpm-lock.yaml') }}-
      - name: Install dependencies
        working-directory: ./bondage-academy
        run: pnpm install --frozen-lockfile
      - name: Build, test and lint
        working-directory: ./bondage-academy
        run: pnpm nx run-many -t build test lint --parallel=3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push bondage-academy-client Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bondage-academy
          file: ./bondage-academy/apps/bondage-academy-client/Dockerfile
          push: true
          tags: ghcr.io/xenonrope/bondage-academy-client
      - name: Build and push bondage-academy-server Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bondage-academy
          file: ./bondage-academy/apps/bondage-academy-server/Dockerfile
          push: true
          tags: ghcr.io/xenonrope/bondage-academy-server
